### ISSUE TITLE
oriole init fails with unexpected token i in JSON

### ISSUE THREAD

**Issue by brleinad** [AttilaTheHen/oriole#56]
I did a `oriole setup` added my personal access token and account ID and then when running `oriole init` inside a repo I got the following:
```
> oriole init
🕐  Loading...
/Users/danielrb/open/oriole/node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js:53
        throw ex;
        ^

SyntaxError: Unexpected token i in JSON at position 8
    at JSON.parse (<anonymous>)
    at /Users/danielrb/open/oriole/build/commands/init.js:857:25
```

I will continue to investigate but any help would be useful.

**Comment by brleinad** [comment]
I was able to get it working by
1. I ran `oriole setup` again and made sure I had the right info
2. Navigated to the top directory of the repo (I noticed I was not at the top directory of the repo earlier, not sure if this is related)
3. Ran `oriole init` again and this time it worked 🎉

**Comment by injoongy** [comment]
Nice - this is a great find. I don't think I've tested running `init` inside folders in a repo, and not at the top level. I'll investigate this further and see if a fix is needed - thanks!
